---

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm

- name: initialize k8s cluster with kubeadm
  command: kubeadm init --apiserver-advertise-address={{ k8s_init_node_ip }} \
                        --apiserver-cert-extra-sans={{ k8s_init_node_ip }} \
                        --node-name {{ k8s_init_node_name }} \
                        --pod-network-cidr={{ k8s_init_cidr }}
  args:
    creates: /etc/kubernetes/admin.conf

- name: configure superuser to run kubectl
  block:
    - name: create directory .kube
      file:
        path: /root/.kube
        state: directory
    - name: symlink config
      file:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        state: link
